// Builds src/generated/data.js from the market-data snapshot in assets/data
// (refresh it with scripts/fetch-data.mjs) plus Natural Earth land polygons for the dotted globe.
// Runs fully offline so the same snapshot always renders the same video.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TILES, coinId } from './tiles.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const D = (f) => path.join(ROOT, 'assets', 'data', f);
const J = (f) => JSON.parse(fs.readFileSync(D(f), 'utf8'));

// ---- tickers (main dex + HIP-3 "xyz" dex) ----
function ctxMap(file, strip = '') {
  const [meta, ctx] = J(file);
  const m = {};
  meta.universe.forEach((u, i) => {
    if (u.isDelisted) return;
    const c = ctx[i];
    m[u.name.replace(strip, '')] = { coin: u.name, px: +c.markPx, prev: +c.prevDayPx, vol: +c.dayNtlVlm, oi: +c.openInterest * +c.markPx, lev: u.maxLeverage };
  });
  return m;
}
const DEX = { main: ctxMap('metaAndAssetCtxs.json'), xyz: ctxMap('hip3_xyz.json', 'xyz:') };
const SPARK = J('sparklines.json');

const tiles = [];
for (const [label, key, dex, cat] of TILES) {
  const a = DEX[dex][key];
  if (!a) { console.warn('missing', key); continue; }
  const spark = SPARK[coinId(key, dex)] || [];
  tiles.push({ label, cat, px: a.px, chg: +((a.px / a.prev - 1) * 100).toFixed(2), lev: a.lev, spark: spark.map((v) => +v.toPrecision(6)) });
}

// ---- BTC order book, trades, candles ----
const l2 = J('l2_BTC.json');
const book = {
  bids: l2.levels[0].slice(0, 16).map((l) => [+l.px, +l.sz, l.n]),
  asks: l2.levels[1].slice(0, 16).map((l) => [+l.px, +l.sz, l.n]),
  time: l2.time,
};
const trades = J('trades_BTC.json').slice(0, 24).map((t) => [+t.px, +t.sz, t.side === 'B' ? 1 : -1]);
const btc15 = J('candles_BTC_15m.json').map((c) => [+c.o, +c.h, +c.l, +c.c, +c.v]);
const hype1d = J('candles_HYPE_1d.json').map((c) => +c.c);

// ---- volume + users history (official stats backend) ----
const vol = J('stats_daily_usd_volume.json').chart_data;
const weekly = [];
for (let i = 0; i < vol.length; i += 7) weekly.push(+(vol.slice(i, i + 7).reduce((a, x) => a + x.daily_usd_volume, 0) / 1e9).toFixed(2));
const users = J('stats_cumulative_new_users.json').chart_data;
const usersWeekly = [];
for (let i = 0; i < users.length; i += 7) usersWeekly.push(users[i].cumulative_new_users);

// ---- market counts ----
const mainLive = Object.keys(DEX.main).length;
let hip3Live = 0;
for (const f of fs.readdirSync(path.join(ROOT, 'assets', 'data')).filter((f) => f.startsWith('hip3_'))) {
  try {
    const [meta] = J(f);
    hip3Live += meta.universe.filter((u) => !u.isDelisted).length;
  } catch { /* dex without markets */ }
}
const spot = J('spotMetaAndAssetCtxs.json')[0].universe.length;
const oiMain = Object.values(DEX.main).reduce((a, x) => a + x.oi, 0);

// ---- dotted globe: Fibonacci sphere points that fall on land ----
const land = J('ne_110m_land.geojson').features;
const rings = [];
for (const f of land) {
  const g = f.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  for (const p of polys) rings.push(p[0]);
}
const bbox = rings.map((r) => {
  let x0 = 1e9, x1 = -1e9, y0 = 1e9, y1 = -1e9;
  for (const [x, y] of r) { x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y); }
  return [x0, x1, y0, y1];
});
const inRing = (r, x, y) => {
  let c = false;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
    const [xi, yi] = r[i], [xj, yj] = r[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) c = !c;
  }
  return c;
};
const onLand = (lon, lat) => rings.some((r, k) => lon >= bbox[k][0] && lon <= bbox[k][1] && lat >= bbox[k][2] && lat <= bbox[k][3] && inRing(r, lon, lat));
const globe = [];
const NP = 26000;
const GA = Math.PI * (3 - Math.sqrt(5));
for (let i = 0; i < NP; i++) {
  const y = 1 - (i / (NP - 1)) * 2;
  const lat = (Math.asin(y) * 180) / Math.PI;
  const lon = ((((i * GA * 180) / Math.PI) % 360) + 540) % 360 - 180;
  if (lat < -60) continue;
  if (onLand(lon, lat)) globe.push(+lat.toFixed(2), +lon.toFixed(2));
}

const DATA = {
  asOf: new Date(book.time).toISOString(),
  tiles, book, trades, btc15, hype1d,
  weeklyVolumeB: weekly, volumeRange: [vol[0].time.slice(0, 10), vol[vol.length - 1].time.slice(0, 10)],
  usersWeekly,
  counts: { perpMain: mainLive, perpHip3: hip3Live, spotPairs: spot, oiMainB: +(oiMain / 1e9).toFixed(2) },
  globe,
};
fs.writeFileSync(path.join(ROOT, 'src', 'generated', 'data.js'), '// Generated by scripts/prep-data.mjs from the public Hyperliquid API snapshot.\nexport const DATA = ' + JSON.stringify(DATA) + ';\n');
console.log('tiles', tiles.length, '| book', book.bids.length, book.asks.length, '| trades', trades.length, '| btc15', btc15.length,
  '| weekly vol', weekly.length, '| counts', JSON.stringify(DATA.counts), '| globe dots', globe.length / 2);
