// Extracts the Hyperliquid mark + wordmark paths from the official homepage SVG
// into src/generated/logo.js (path data + bounding boxes, letters ordered left to right).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const svg = fs.readFileSync(path.join(ROOT, 'assets/brand/logo_wordmark.svg'), 'utf8');
const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);

// Sample points along a path (control polygon + bezier samples) to get a tight-enough bbox.
function bbox(d) {
  const tok = d.match(/[a-zA-Z]|-?(?:\d+\.?\d*|\.\d+)(?:e-?\d+)?/g);
  let i = 0, cmd = '', x = 0, y = 0, sx = 0, sy = 0, lcx = 0, lcy = 0;
  const pts = [];
  const num = () => parseFloat(tok[i++]);
  const cubic = (x0, y0, x1, y1, x2, y2, x3, y3) => {
    for (let k = 1; k <= 12; k++) {
      const t = k / 12, u = 1 - t;
      pts.push([u * u * u * x0 + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t * t * t * x3, u * u * u * y0 + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t * t * t * y3]);
    }
  };
  while (i < tok.length) {
    if (/[a-zA-Z]/.test(tok[i])) cmd = tok[i++];
    const rel = cmd === cmd.toLowerCase();
    const C = cmd.toUpperCase();
    if (C === 'Z') { x = sx; y = sy; continue; }
    if (C === 'M') { const nx = num() + (rel ? x : 0), ny = num() + (rel ? y : 0); x = sx = nx; y = sy = ny; pts.push([x, y]); cmd = rel ? 'l' : 'L'; continue; }
    if (C === 'L') { x = num() + (rel ? x : 0); y = num() + (rel ? y : 0); pts.push([x, y]); continue; }
    if (C === 'H') { x = num() + (rel ? x : 0); pts.push([x, y]); continue; }
    if (C === 'V') { y = num() + (rel ? y : 0); pts.push([x, y]); continue; }
    if (C === 'C') {
      const x1 = num() + (rel ? x : 0), y1 = num() + (rel ? y : 0), x2 = num() + (rel ? x : 0), y2 = num() + (rel ? y : 0), x3 = num() + (rel ? x : 0), y3 = num() + (rel ? y : 0);
      cubic(x, y, x1, y1, x2, y2, x3, y3); lcx = x2; lcy = y2; x = x3; y = y3; continue;
    }
    if (C === 'S') {
      const x1 = 2 * x - lcx, y1 = 2 * y - lcy;
      const x2 = num() + (rel ? x : 0), y2 = num() + (rel ? y : 0), x3 = num() + (rel ? x : 0), y3 = num() + (rel ? y : 0);
      cubic(x, y, x1, y1, x2, y2, x3, y3); lcx = x2; lcy = y2; x = x3; y = y3; continue;
    }
    if (C === 'Q') { const x1 = num() + (rel ? x : 0), y1 = num() + (rel ? y : 0); x = num() + (rel ? x : 0); y = num() + (rel ? y : 0); pts.push([x1, y1], [x, y]); continue; }
    throw new Error('unsupported command ' + cmd);
  }
  const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
  return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)].map((v) => +v.toFixed(2));
}

const items = ds.map((d) => ({ d, bbox: bbox(d) }));
const symbol = items[0];
const letters = [];
for (const it of items.slice(1).sort((a, b) => a.bbox[0] - b.bbox[0])) {
  if (letters.some((l) => Math.abs(l.bbox[0] - it.bbox[0]) < 1 && Math.abs(l.bbox[2] - it.bbox[2]) < 1)) continue; // duplicate glyph
  letters.push(it);
}
const out = { viewBox: [0, 0, 856, 200], symbol, letters };
fs.writeFileSync(path.join(ROOT, 'src', 'generated', 'logo.js'), '// Generated by scripts/prep-logo.mjs from the hyperliquid.xyz header SVG.\nexport const LOGO = ' + JSON.stringify(out) + ';\n');
console.log('symbol', symbol.bbox, '\nletters', letters.map((l) => l.bbox.join(',')).join(' | '));
